import { mkdir, writeFile } from "node:fs/promises"
import { fileURLToPath } from "node:url"
import {
  paletteColorRoles,
  palettes,
  type PaletteColorRole,
} from "../src/data/palettes"

const outputUrl = new URL("../src/generated/palettes.scss", import.meta.url)

const toCssName = (role: PaletteColorRole) =>
  role.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)

const colorToRgb = (color: string) => {
  const value = color.slice(1)
  return [0, 2, 4].map((offset) =>
    Number.parseInt(value.slice(offset, offset + 2), 16)
  )
}

const luminance = (color: string) => {
  const channels = colorToRgb(color).map((channel) => {
    const normalized = channel / 255
    return normalized <= 0.03928
      ? normalized / 12.92
      : ((normalized + 0.055) / 1.055) ** 2.4
  })

  return channels[0] * 0.2126 + channels[1] * 0.7152 + channels[2] * 0.0722
}

const contrast = (first: string, second: string) => {
  const firstLuminance = luminance(first)
  const secondLuminance = luminance(second)
  const lighter = Math.max(firstLuminance, secondLuminance)
  const darker = Math.min(firstLuminance, secondLuminance)
  return (lighter + 0.05) / (darker + 0.05)
}

const assertContrast = (
  paletteName: string,
  foreground: string,
  background: string,
  minimum: number,
  label: string
) => {
  const ratio = contrast(foreground, background)
  if (ratio < minimum) {
    throw new Error(
      `${paletteName}: ${label} contrast is ${ratio.toFixed(2)}; expected at least ${minimum}.`
    )
  }
}

const seenIds = new Set<string>()
for (const palette of palettes) {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(palette.id)) {
    throw new Error(`${palette.name}: palette ID must be kebab-case.`)
  }
  if (seenIds.has(palette.id)) {
    throw new Error(`${palette.name}: duplicate palette ID ${palette.id}.`)
  }
  seenIds.add(palette.id)

  for (const role of paletteColorRoles) {
    if (!/^#[0-9A-F]{6}$/.test(palette.colors[role])) {
      throw new Error(
        `${palette.name}: ${role} must be a six-digit uppercase hex color.`
      )
    }
  }

  assertContrast(
    palette.name,
    palette.colors.ink,
    palette.colors.canvas,
    4.5,
    "ink on canvas"
  )
  assertContrast(
    palette.name,
    palette.colors.muted,
    palette.colors.canvas,
    4.5,
    "muted ink on canvas"
  )
  assertContrast(
    palette.name,
    palette.colors.accentInk,
    palette.colors.accent,
    4.5,
    "accent ink on accent"
  )
  assertContrast(
    palette.name,
    palette.colors.focus,
    palette.colors.canvas,
    3,
    "focus on canvas"
  )
}

const declarations = (palette: (typeof palettes)[number]) =>
  paletteColorRoles
    .map((role) => `  --color-${toCssName(role)}: ${palette.colors[role]};`)
    .join("\n")

const css = `${[
  "// Generated by scripts/generate-palettes.ts. Edit src/data/palettes.ts instead.",
  `:root {\n${declarations(palettes[0])}\n}`,
  ...palettes.map(
    (palette) => `[data-palette="${palette.id}"] {\n${declarations(palette)}\n}`
  ),
].join("\n\n")}\n`

await mkdir(fileURLToPath(new URL("../src/generated/", import.meta.url)), {
  recursive: true,
})
await writeFile(fileURLToPath(outputUrl), css)

console.log(`Generated ${palettes.length} palettes.`)
